### ISSUE TITLE
Failure in transform for highway.endswith('_link') when NoneType

### ISSUE THREAD

**Issue by nvkelso** [tilezen/TileStache#144]
```
127.0.0.1 - - [18/Apr/2016 23:54:06] "GET /all/12/656/1583.topojson HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/Users/nvkelso/git-repos/tileserver/tileserver/__init__.py", line 188, in __call__
    response = self.handle_request(request)
  File "/Users/nvkelso/git-repos/tileserver/tileserver/__init__.py", line 284, in handle_request
    [], [])
  File "/Library/Python/2.7/site-packages/tilequeue/process.py", line 397, in process_coord
    padded_bounds, scale, layers_to_format)
  File "/Library/Python/2.7/site-packages/tilequeue/process.py", line 316, in _process_feature_layers
    shape, props, feature_id, coord.zoom)
  File "/Library/Python/2.7/site-packages/TileStache/Goodies/VecTiles/server.py", line 45, in transform_fn
    shape, properties, fid = fn(shape, properties, fid, zoom)
  File "/Library/Python/2.7/site-packages/TileStache/Goodies/VecTiles/transform.py", line 283, in road_classifier
    if highway.endswith('_link'):
AttributeError: 'NoneType' object has no attribute 'ends with'
```

**Comment by nvkelso** [comment]
I get this error when upgrading to the new YAML driven road classifier. Doesn't fail on every tile, but around 1/2 of them.

**Comment by zerebubuth** [comment]
I'm pretty sure that this has the same root cause as https://github.com/mapzen/vector-datasource/issues/732 - the update to tilequeue which sweeps those `null`s is missing, and so the assumption that if a value is present it's not `null` / `None` doesn't hold. Specifically, we get `highway` in a way which fills missing values with an empty string, but which doesn't protect against `None` being a value in that `dict`.

Please update tilequeue (and TileStache) as recommended in https://github.com/mapzen/vector-datasource/issues/732 and let me know if you're still seeing this.

**Comment by nvkelso** [comment]
Yep, a 100% manual reinstall of both TileStache integration-1 and tilequeue master was required in those checkouts fixes these issues.
