### ISSUE TITLE
creating mvt tiles

### ISSUE THREAD

**Issue by jbants** [tilezen/TileStache#160]
I'm trying to create .mvt tiles from a postgis backend and am getting a too many values to unpack error when i request the tile.

``` python
Traceback (most recent call last):
  File "/virtualenv/tilefarm/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/webapps/website/tilefarm/apps/layers/views.py", line 91, in tiles
    status_code, headers, content = tilestacheLayer.getTileResponse(coord, extension)
  File "/virtualenv/tilefarm/local/lib/python2.7/site-packages/TileStache/Core.py", line 431, in getTileResponse
    tile.save(buff, format, **save_kwargs)
  File "/virtualenv/tilefarm/local/lib/python2.7/site-packages/TileStache/Goodies/VecTiles/server.py", line 342, in save
    mvt.encode(out, features, self.coord, self.layer_name)
  File "/virtualenv/tilefarm/local/lib/python2.7/site-packages/TileStache/Goodies/VecTiles/mvt.py", line 21, in encode
    data = mapbox_vector_tile.encode(layers, quantize_bounds=bounds)
  File "/virtualenv/tilefarm/local/lib/python2.7/site-packages/mapbox_vector_tile/__init__.py", line 16, in encode
    quantize_bounds, y_coord_down)
  File "/virtualenv/tilefarm/local/lib/python2.7/site-packages/mapbox_vector_tile/encoder.py", line 97, in addFeatures
    shape = self.quantize(shape, quantize_bounds)
  File "/virtualenv/tilefarm/local/lib/python2.7/site-packages/mapbox_vector_tile/encoder.py", line 123, in quantize
    minx, miny, maxx, maxy = bounds
ValueError: too many values to unpack
```

my config is being generated dynamically but the json parameters and sql query that im using are:

``` json
{
  "dbinfo": {
    "host": "", 
    "password": "", 
    "user": "", 
    "database": ""
  }, 
  "clip": false, 
  "queries": [
    "SELECT ST_Transform(wkb_geometry,900913) as __geometry__ FROM map_regionscheme_301"
  ]
}
```

Is this the correct query to be using with the mvt layers?
Requesting json tiles using the above config works fine.

Thanks.

**Comment by rmarianski** [comment]
It's a bug. The issue is that the server code there has fallen out of date with the encoder. The line at fault looks to be this one:

```
File "/virtualenv/tilefarm/local/lib/python2.7/site-packages/TileStache/Goodies/VecTiles/server.py", line 342, in save
    mvt.encode(out, features, self.coord, self.layer_name)
```

If you're willing to make an update there to get it working for you, we'd accept a pr for it.

Otherwise, I'd suggest looking to see if you can get things working by following [these instructions](https://github.com/mapzen/vector-datasource/wiki/Mapzen-Vector-Tile-Service). That setup and the queries are very specific to our environment and data, but it's the setup that we are running. You may be able to get things working by specifying an alternate queries.yaml with your queries, but to my knowledge nobody has tried that.

**Comment by jbants** [comment]
Ok thanks. I'll mess around and see what i can break ;)
Thanks for doing the leg work on the mvt encoding.
