### ISSUE TITLE
Error when calling difference

### ISSUE THREAD

**Issue by rmarianski** [tilezen/TileStache#77]
The error below suggests that we are generating invalid geometries at some point. It seems to fail when calling [boundary difference](https://github.com/mapzen/TileStache/blob/355af65db2609b13f3924012f95e3a17d0994300/TileStache/Goodies/VecTiles/transform.py#L1384) in the exterior boundaries transform.

2015-10-23_21:18:19.53441 process - ERROR - Error processing: 10/293/404 - Traceback (most recent call last): |   File "/usr/local/lib/python2.7/dist-packages/tilequeue/worker.py", line 238, in **call**    cut_coords) |   File "/usr/local/lib/python2.7/dist-packages/tilequeue/process.py", line 330, in process_coord    padded_bounds, scale) |   File "/usr/local/lib/python2.7/dist-packages/tilequeue/process.py", l$ne 272, in _process_feature_layers    processed_feature_layers, post_process_data, coord.zoom) |   File "/usr/local/lib/python2.7/dist-packages/tilequeue/process.py", line 73, in _postprocess_data    layer = fn(feature_layers, zoom, **params) |   File "/usr/local/lib/python2.7/dist-packages/TileStache/Goodies/VecTiles/transform.py", line 1384, in exterior_boundaries    boundary = boundary.difference(buf) |   Fil$ "/usr/local/lib/python2.7/dist-packages/shapely/geometry/base.py", line 527, in difference    return geom_factory(self.impl['difference'](self, other)) |   File "/usr/local/lib/python2.7/dist-packages/shape$y/topology.py", line 50, in __call__    "The operation '%s' produced a null geometry. Likely cause is invalidity of the 'other' geometry %s" % (self.fn.**name**, repr(other))) | TopologicalError: The operati$n 'GEOSDifference_r' produced a null geometry. Likely cause is invalidity of the 'other' geometry <shapely.geometry.polygon.Polygon object at 0x7f235a473990>

**Comment by zerebubuth** [comment]
Seems to be caused by [relation 1224047](http://www.openstreetmap.org/relation/1224047) which is a _huge_ riverbank imported (badly - seems nodes/ways aren't joined across boundaries) from NHD. The problem area isn't so much with that the polygon is invalid - it isn't in the database. By the time we get to it, it has become invalid. Below is the dump of the failed geometry in purple and the original from the database in yellow behind it. Note that this is very, very small.

![relation_1224047_invalid](https://cloud.githubusercontent.com/assets/271360/10734814/0910908c-7bfd-11e5-810a-e073cc0542e7.png)

I'll start trying to figure out where in the pipeline it's becoming invalid.
